# Generated by Django 6.1 on 2026-09-01 17:33

import django.contrib.auth.models
import users.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('object', users.managers.CustomUserManager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='area_street',
            field=models.CharField(max_length=250),
        ),
    ]
